/*
 * Filename: sc_input_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass
 * name: sc_input
 * shortname: input
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_input_type.h"



/* USER CODE START SC_INPUT_INCLUDE */
#include "stdlib.h"
/* USER CODE END SC_INPUT_INCLUDE */




/* USER CODE START SC_INPUT_USERDEFINITIONS */

/* USER CODE END SC_INPUT_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_INPUT signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_INPUT_driverIn(SC_INPUT_data_t *const data)
{
	/* USER CODE START driverInSC_INPUT */
data->m_ev = EV_NONE;
    data->Button_L_Status = Button_1_Read();
    data->Button_R_Status = Button_2_Read();
	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_INPUT */
}



