/*
 * Filename: swc_clock.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component that displays time (hours and minutes)
 * name: swc_clock
 * shortname: clock
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_clock.h"



/* USER CODE START SWC_CLOCK_INCLUDE */
#include "stdlib.h"
/* USER CODE END SWC_CLOCK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CLOCK_USERDEFINITIONS */

/* USER CODE END SWC_CLOCK_USERDEFINITIONS */



/*
 * component: swc_clock
 * cycletime: 50
 * description: Runnable
 * events: 
 * name: CLOCK_input_run
 * shortname: input
 * signalIN: 
 * signalOUT: so_input
 * task: tsk_input
 */
void CLOCK_input_run(RTE_event ev){
	
	/* USER CODE START CLOCK_input_run */
    char buffer[100];
    RTE_SC_INPUT_pullPort(&SO_INPUT_signal);
    SC_INPUT_data_t input = RTE_SC_INPUT_get(&SO_INPUT_signal);
    
    static uint16_t left_key_flag = 0;
    static uint16_t right_key_flag = 0;
    static uint16_t tick_longpress = 0;
    
    static uint16_t tick_1min = 0;
    static uint16_t tick_250ms = 0;

    
    if(tick_250ms == 250)
    {
        input.m_ev = EV_250MS;
        tick_250ms = 0;
    }
    else
    {
        tick_250ms = tick_250ms+50;
    }
    
    if(tick_1min == 60000)
    {
        input.m_ev = EV_1MIN;
        tick_1min = 0;
    }
    else
    {
        tick_1min = tick_1min + 50;
    }

    if(input.Button_L_Status == 1)
    {
        //UART_LOG_PutString("left key Pressed\n");
        left_key_flag = 1;
    }
    if(input.Button_R_Status == 1)
    {
        //UART_LOG_PutString("right key Pressed\n");
        right_key_flag = 1;
        tick_longpress += 100;
        /*
        itoa(tick_longpress, buffer, 10);
        UART_LOG_PutString(buffer);
        UART_LOG_PutString("\n");
        */
    }
    
    if(input.Button_L_Status == 0 && left_key_flag == 1)
    {
        input.m_ev = EV_KEYLEFT;
        left_key_flag = 0;
    }
    else if (input.Button_R_Status == 0 && right_key_flag == 1 && tick_longpress < 1000)
    {
        input.m_ev = EV_KEYRIGHT;
        right_key_flag = 0;
        tick_longpress = 0;   
    }
    else if(input.Button_R_Status == 0 && right_key_flag == 1 && tick_longpress > 1000)
    {
        input.m_ev = EV_KEYRIGHTLONGPRESS;
        right_key_flag = 0;
        tick_longpress = 0;
    }
    RTE_SC_INPUT_set(&SO_INPUT_signal, input);
    /* USER CODE END CLOCK_input_run */
}

/*
 * component: swc_clock
 * cycletime: 0
 * description: Runnable
 * events: ev_onData|ev_button
 * name: CLOCK_control_run
 * shortname: control
 * signalIN: so_input
 * signalOUT: so_control
 * task: tsk_control
 */
void CLOCK_control_run(RTE_event ev){
	
	/* USER CODE START CLOCK_control_run */
    SC_INPUT_data_t input;
    /*char buffer[100];
    itoa(input.m_ev,buffer,10);
    UART_LOG_PutString("ev: in clk ");
    UART_LOG_PutString(buffer);
    UART_LOG_PutString("\n");*/
    input = RTE_SC_INPUT_get(&SO_INPUT_signal);
    
    if(input.m_ev == EV_KEYLEFT)
    {
        //UART_LOG_PutString("left key ev\n");
        ProcessEvent(EV_KEYLEFT);
    }
    else if(input.m_ev == EV_KEYRIGHT)
    {
        //UART_LOG_PutString("right key ev\n");
        ProcessEvent(EV_KEYRIGHT);
    }
    else if(input.m_ev == EV_KEYRIGHTLONGPRESS)
    {
        ProcessEvent(EV_KEYRIGHTLONGPRESS);
    }
    else if(input.m_ev == EV_1MIN)
    {
        ProcessEvent(input.m_ev);
    }
    else if(input.m_ev == EV_250MS)
    {
        ProcessEvent(input.m_ev);
    }
    /* USER CODE END CLOCK_control_run */
}

/*
 * component: swc_clock
 * cycletime: 250
 * description: Runnable
 * events: 
 * name: CLOCK_display_run
 * shortname: display
 * signalIN: so_control
 * signalOUT: so_display
 * task: tsk_input
 */
void CLOCK_display_run(RTE_event ev){
	
	/* USER CODE START CLOCK_display_run */
    SC_DISPLAY_data_t display = SC_DISPLAY_INIT_DATA;
    SC_CONTROL_data_t control = SC_CONTROL_INIT_DATA;
    control = RTE_SC_CONTROL_get(&SO_CONTROL_signal);
    display.hour = control.hour;
    display.minute = control.minute;
    
    RTE_SC_DISPLAY_set(&SO_DISPLAY_signal, display);
    RTE_SC_DISPLAY_pushPort(&SO_DISPLAY_signal);
    /* USER CODE END CLOCK_display_run */
}

/* USER CODE START SWC_CLOCK_FUNCTIONS */

/* USER CODE END SWC_CLOCK_FUNCTIONS */

